apps:
  grafana:
    namespace: grafana
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: grafana
  # sonarqube:
  #   namespace: sonarqube
  #   repoURL: https://github.com/vidojeg/k8s.git
  #   targetRevision: master
  #   path: sonarqube