apps:
  grafana:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: grafana
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube