apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  helm-dashboard:
    helm_chart_repo: https://helm-charts.komodor.io
    helm_chart: helm-dashboard
    helm_chart_version: 0.1.10
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  crossplane:
    helm_chart_repo: https://charts.crossplane.io/stable
    helm_chart: crossplane
    helm_chart_version: 1.13.2
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  komoplane:
    helm_chart_repo: https://helm-charts.komodor.io
    helm_chart: komoplane
    helm_chart_version: 0.1.4
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
