apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  prometheus:
    helm_chart_repo: https://prometheus-community.github.io/helm-charts
    helm_chart: kube-prometheus-stack
    helm_chart_version: 45.9.1
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  cert-manager:
    helm_chart_repo: https://charts.jetstack.io
    helm_chart: cert-manager
    helm_chart_version: 1.11.0
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main