apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  grafana:
    helm_chart_repo: https://grafana.github.io/helm-charts
    helm_chart: grafana
    helm_chart_version: 6.58.4
    value_file_url: git@github.com:Stellantis-ADX/engineering-platform.git
    value_revision: main

