apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  jenkins:
    helm_chart_repo: https://charts.jenkins.io/
    helm_chart: jenkins
    helm_chart_version: 2.18.2
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  crossplane:
    helm_chart_repo: https://charts.crossplane.io/master/
    helm_chart: crossplane
    helm_chart_version: 1.13.0-rc.0.239.g864e0d11
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main