apps: {}

helm:
  jenkins: 
    helm_chart_repo: https://charts.jenkins.io
    helm_chart: jenkins
    helm_chart_version: 4.3.23
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  cert-manager:
    helm_chart_repo: https://charts.jetstack.io
    helm_chart: cert-manager
    helm_chart_version: 1.11.0
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
