apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  cert-manager:
    helm_chart_repo: https://charts.jetstack.io
    helm_chart: cert-manager
    helm_chart_version: 1.11.0
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
