apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube
  tekton-dashboard:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: tekton-dashboard
    namespace: tekton-pipelines
  java-ci:
    repoURL: https://github.com/vidojeg/java-tekton-ci.git
    targetRevision: main
    path: .
    namespace: tekton-pipelines

helm:
  helm-dashboard:
    helm_chart_repo: https://helm-charts.komodor.io
    helm_chart: helm-dashboard
    helm_chart_version: 0.1.10
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  tekton-pipelines:
    helm_chart_repo: https://cdfoundation.github.io/tekton-helm-chart/
    helm_chart: tekton-pipeline
    helm_chart_version: 1.0.2
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
  cert-manager:
    helm_chart_repo: https://charts.jetstack.io
    helm_chart: cert-manager
    helm_chart_version: 1.15.0
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
