apps:
  sonarqube:
    repoURL: https://github.com/vidojeg/k8s.git
    targetRevision: master
    path: sonarqube

helm:
  jenkins:
    helm_chart_repo: https://charts.jenkins.io/
    helm_chart: jenkins
    helm_chart_version: 4.3.23
    value_file_url: https://github.com/vidojeg/helm-values.git
    value_revision: main
