{{ range $key, $value := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $key }}
    server: https://kubernetes.default.svc
  project: {{ $key }}
  source:
    path: {{ default "." $value.path }}
    repoURL: {{ $value.repoURL }}
    targetRevision: {{ $value.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: {{ $key }}
      server: https://kubernetes.default.svc
  sourceRepos:
    -  {{ $value.repoURL }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
status: {}
{{ end }}