{{ range $key, $value := .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $value.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ $value.path }}
    repoURL: {{ $value.repoURL }}
    targetRevision: {{ $value.targetRevision }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
{{ end }}