{{- range $key, $val := .Values.helm }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $key }}
    server: https://kubernetes.default.svc
  project: {{ $key }}
  sources:
    - repoURL: {{ $val.helm_chart_repo }}
      chart: {{ $val.helm_chart }}
      targetRevision: {{ $val.helm_chart_version }}
      helm:
        valueFiles:
          - $values/{{ $key }}/values.yaml
    - repoURL: {{ $val.value_file_url }}
      targetRevision: {{ $val.value_revision }}
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: {{ default $key $value.namespace }}
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  sourceRepos:
    -  {{ $val.helm_chart_repo }}
    -  {{ $val.value_file_url }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
status: {}  
{{ end -}}

